services:
  ecom-database:
    platform: linux/amd64
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data # save data between restarts
    ports:
      - 5432:5432

  ecom-app:
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/ecom
      - nodemodules:/ecom/node_modules
    depends_on:
      - ecom-database

volumes:
  db_data:
  nodemodules:
