services:
  ecom-database:
    platform: linux/amd64
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ecom-db:/var/lib/postgresql/data # save data between restarts
    ports:
      - 5432:5432

  ecom-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    depends_on:
      - ecom-database

volumes:
  ecom-db:
    name: ecom-db
    external: true
  nodemodules: {}