import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Poppins } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: '400' })
const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.className} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
