name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: 22fsantos/ecommerce:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-50-17-20-5.compute-1.amazonaws.com 'sudo docker pull 22fsantos/ecommerce:latest'

    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-50-17-20-5.compute-1.amazonaws.com 'sudo docker stop ecommerce || true'
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-50-17-20-5.compute-1.amazonaws.com 'sudo docker rm ecommerce || true'

    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-50-17-20-5.compute-1.amazonaws.com 'sudo docker run -d --name ecommerce -p 80:3000 22fsantos/ecommerce:latest'
